export * from './icons';

export const countriesCode = [
  {
    country: 'Afghanistan',
    code: 'AF',
    value: '+93',
    icon: '🇦🇫',
  },
  {
    country: 'Albania',
    code: 'AL',
    value: '+355',
    icon: '🇦🇱',
  },
  {
    country: 'Algeria',
    code: 'DZ',
    value: '+213',
    icon: '🇩🇿',
  },
  {
    country: 'Andorra',
    code: 'AD',
    value: '+376',
    icon: '🇦🇩',
  },
  {
    country: 'Angola',
    code: 'AO',
    value: '+244',
    icon: '🇦🇴',
  },
  {
    country: 'Antigua and Barbuda',
    code: 'AG',
    value: '+1-268',
    icon: '🇦🇬',
  },
  {
    country: 'Argentina',
    code: 'AR',
    value: '+54',
    icon: '🇦🇷',
  },
  {
    country: 'Armenia',
    code: 'AM',
    value: '+374',
    icon: '🇦🇲',
  },
  {
    country: 'Australia',
    code: 'AU',
    value: '+61',
    icon: '🇦🇺',
  },
  {
    country: 'Austria',
    code: 'AT',
    value: '+43',
    icon: '🇦🇹',
  },
  {
    country: 'Azerbaijan',
    code: 'AZ',
    value: '+994',
    icon: '🇦🇿',
  },
  {
    country: 'Bahamas',
    code: 'BS',
    value: '+1-242',
    icon: '🇧🇸',
  },
  {
    country: 'Bahrain',
    code: 'BH',
    value: '+973',
    icon: '🇧🇭',
  },
  {
    country: 'Bangladesh',
    code: 'BD',
    value: '+880',
    icon: '🇧🇩',
  },
  {
    country: 'Barbados',
    code: 'BB',
    value: '+1-246',
    icon: '🇧🇧',
  },
  {
    country: 'Belarus',
    code: 'BY',
    value: '+375',
    icon: '🇧🇾',
  },
  {
    country: 'Belgium',
    code: 'BE',
    value: '+32',
    icon: '🇧🇪',
  },
  {
    country: 'Belize',
    code: 'BZ',
    value: '+501',
    icon: '🇧🇿',
  },
  {
    country: 'Benin',
    code: 'BJ',
    value: '+229',
    icon: '🇧🇯',
  },
  {
    country: 'Bhutan',
    code: 'BT',
    value: '+975',
    icon: '🇧🇹',
  },
  {
    country: 'Bolivia',
    code: 'BO',
    value: '+591',
    icon: '🇧🇴',
  },
  {
    country: 'Bosnia and Herzegovina',
    code: 'BA',
    value: '+387',
    icon: '🇧🇦',
  },
  {
    country: 'Botswana',
    code: 'BW',
    value: '+267',
    icon: '🇧🇼',
  },
  {
    country: 'Brazil',
    code: 'BR',
    value: '+55',
    icon: '🇧🇷',
  },
  {
    country: 'Brunei',
    code: 'BN',
    value: '+673',
    icon: '🇧🇳',
  },
  {
    country: 'Bulgaria',
    code: 'BG',
    value: '+359',
    icon: '🇧🇬',
  },
  {
    country: 'Burkina Faso',
    code: 'BF',
    value: '+226',
    icon: '🇧🇫',
  },
  {
    country: 'Burundi',
    code: 'BI',
    value: '+257',
    icon: '🇧🇮',
  },
  {
    country: 'Cabo Verde',
    code: 'CV',
    value: '+238',
    icon: '🇨🇻',
  },
  {
    country: 'Cambodia',
    code: 'KH',
    value: '+855',
    icon: '🇰🇭',
  },
  {
    country: 'Cameroon',
    code: 'CM',
    value: '+237',
    icon: '🇨🇲',
  },
  {
    country: 'Canada',
    code: 'CA',
    value: '+1',
    icon: '🇨🇦',
  },
  {
    country: 'Central African Republic',
    code: 'CF',
    value: '+236',
    icon: '🇨🇫',
  },
  {
    country: 'Chad',
    code: 'TD',
    value: '+235',
    icon: '🇹🇩',
  },
  {
    country: 'Chile',
    code: 'CL',
    value: '+56',
    icon: '🇨🇱',
  },
  {
    country: 'China',
    code: 'CN',
    value: '+86',
    icon: '🇨🇳',
  },
  {
    country: 'Colombia',
    code: 'CO',
    value: '+57',
    icon: '🇨🇴',
  },
  {
    country: 'Comoros',
    code: 'KM',
    value: '+269',
    icon: '🇰🇲',
  },
  {
    country: 'Congo (Congo-Brazzaville)',
    code: 'CG',
    value: '+242',
    icon: '🇨🇬',
  },
  {
    country: 'Congo (DRC)',
    code: 'CD',
    value: '+243',
    icon: '🇨🇩',
  },
  {
    country: 'Costa Rica',
    code: 'CR',
    value: '+506',
    icon: '🇨🇷',
  },
  {
    country: 'Croatia',
    code: 'HR',
    value: '+385',
    icon: '🇭🇷',
  },
  {
    country: 'Cuba',
    code: 'CU',
    value: '+53',
    icon: '🇨🇺',
  },
  {
    country: 'Cyprus',
    code: 'CY',
    value: '+357',
    icon: '🇨🇾',
  },
  {
    country: 'Czechia (Czech Republic)',
    code: 'CZ',
    value: '+420',
    icon: '🇨🇿',
  },

  {
    country: 'Denmark',
    code: 'DK',
    value: '+45',
    icon: '🇩🇰',
  },
  {
    country: 'Djibouti',
    code: 'DJ',
    value: '+253',
    icon: '🇩🇯',
  },
  {
    country: 'Dominica',
    code: 'DM',
    value: '+1-767',
    icon: '🇩🇲',
  },
  {
    country: 'Dominican Republic',
    code: 'DO',
    value: '+1-809',
    icon: '🇩🇴',
  },
  {
    country: 'Ecuador',
    code: 'EC',
    value: '+593',
    icon: '🇪🇨',
  },
  {
    country: 'Egypt',
    code: 'EG',
    value: '+20',
    icon: '🇪🇬',
  },
  {
    country: 'El Salvador',
    code: 'SV',
    value: '+503',
    icon: '🇸🇻',
  },
  {
    country: 'Equatorial Guinea',
    code: 'GQ',
    value: '+240',
    icon: '🇬🇶',
  },
  {
    country: 'Eritrea',
    code: 'ER',
    value: '+291',
    icon: '🇪🇷',
  },
  {
    country: 'Estonia',
    code: 'EE',
    value: '+372',
    icon: '🇪🇪',
  },
  {
    country: 'Eswatini (Swaziland)',
    code: 'SZ',
    value: '+268',
    icon: '🇸🇿',
  },
  {
    country: 'Ethiopia',
    code: 'ET',
    value: '+251',
    icon: '🇪🇹',
  },
  {
    country: 'Fiji',
    code: 'FJ',
    value: '+679',
    icon: '🇫🇯',
  },
  {
    country: 'Finland',
    code: 'FI',
    value: '+358',
    icon: '🇫🇮',
  },
  {
    country: 'France',
    code: 'FR',
    value: '+33',
    icon: '🇫🇷',
  },

  {
    country: 'Gabon',
    code: 'GA',
    value: '+241',
    icon: '🇬🇦',
  },
  {
    country: 'Gambia',
    code: 'GM',
    value: '+220',
    icon: '🇬🇲',
  },
  {
    country: 'Georgia',
    code: 'GE',
    value: '+995',
    icon: '🇬🇪',
  },
  {
    country: 'Germany',
    code: 'DE',
    value: '+49',
    icon: '🇩🇪',
  },
  {
    country: 'Ghana',
    code: 'GH',
    value: '+233',
    icon: '🇬🇭',
  },
  {
    country: 'Greece',
    code: 'GR',
    value: '+30',
    icon: '🇬🇷',
  },
  {
    country: 'Grenada',
    code: 'GD',
    value: '+1-473',
    icon: '🇬🇩',
  },
  {
    country: 'Guatemala',
    code: 'GT',
    value: '+502',
    icon: '🇬🇹',
  },
  {
    country: 'Guinea',
    code: 'GN',
    value: '+224',
    icon: '🇬🇳',
  },
  {
    country: 'Guinea-Bissau',
    code: 'GW',
    value: '+245',
    icon: '🇬🇼',
  },
  {
    country: 'Guyana',
    code: 'GY',
    value: '+592',
    icon: '🇬🇾',
  },
  {
    country: 'Haiti',
    code: 'HT',
    value: '+509',
    icon: '🇭🇹',
  },
  {
    country: 'Honduras',
    code: 'HN',
    value: '+504',
    icon: '🇭🇳',
  },
  {
    country: 'Hungary',
    code: 'HU',
    value: '+36',
    icon: '🇭🇺',
  },
  {
    country: 'Iceland',
    code: 'IS',
    value: '+354',
    icon: '🇮🇸',
  },
  {
    country: 'India',
    code: 'IN',
    value: '+91',
    icon: '🇮🇳',
  },
  {
    country: 'Indonesia',
    code: 'ID',
    value: '+62',
    icon: '🇮🇩',
  },
  {
    country: 'Iran',
    code: 'IR',
    value: '+98',
    icon: '🇮🇷',
  },
  {
    country: 'Iraq',
    code: 'IQ',
    value: '+964',
    icon: '🇮🇶',
  },
  {
    country: 'Ireland',
    code: 'IE',
    value: '+353',
    icon: '🇮🇪',
  },
  {
    country: 'Israel',
    code: 'IL',
    value: '+972',
    icon: '🇮🇱',
  },
  {
    country: 'Italy',
    code: 'IT',
    value: '+39',
    icon: '🇮🇹',
  },
  {
    country: 'Jamaica',
    code: 'JM',
    value: '+1-876',
    icon: '🇯🇲',
  },
  {
    country: 'Japan',
    code: 'JP',
    value: '+81',
    icon: '🇯🇵',
  },
  {
    country: 'Jordan',
    code: 'JO',
    value: '+962',
    icon: '🇯🇴',
  },
  {
    country: 'Kazakhstan',
    code: 'KZ',
    value: '+7',
    icon: '🇰🇿',
  },
  {
    country: 'Kenya',
    code: 'KE',
    value: '+254',
    icon: '🇰🇪',
  },
  {
    country: 'Kiribati',
    code: 'KI',
    value: '+686',
    icon: '🇰🇮',
  },
  {
    country: 'Kuwait',
    code: 'KW',
    value: '+965',
    icon: '🇰🇼',
  },
  {
    country: 'Kyrgyzstan',
    code: 'KG',
    value: '+996',
    icon: '🇰🇬',
  },
  {
    country: 'Laos',
    code: 'LA',
    value: '+856',
    icon: '🇱🇦',
  },
  {
    country: 'Latvia',
    code: 'LV',
    value: '+371',
    icon: '🇱🇻',
  },
  {
    country: 'Lebanon',
    code: 'LB',
    value: '+961',
    icon: '🇱🇧',
  },
  {
    country: 'Lesotho',
    code: 'LS',
    value: '+266',
    icon: '🇱🇸',
  },
  {
    country: 'Liberia',
    code: 'LR',
    value: '+231',
    icon: '🇱🇷',
  },
  {
    country: 'Libya',
    code: 'LY',
    value: '+218',
    icon: '🇱🇾',
  },
  {
    country: 'Liechtenstein',
    code: 'LI',
    value: '+423',
    icon: '🇱🇮',
  },
  {
    country: 'Lithuania',
    code: 'LT',
    value: '+370',
    icon: '🇱🇹',
  },
  {
    country: 'Luxembourg',
    code: 'LU',
    value: '+352',
    icon: '🇱🇺',
  },
  {
    country: 'Madagascar',
    code: 'MG',
    value: '+261',
    icon: '🇲🇬',
  },
  {
    country: 'Malawi',
    code: 'MW',
    value: '+265',
    icon: '🇲🇼',
  },
  {
    country: 'Malaysia',
    code: 'MY',
    value: '+60',
    icon: '🇲🇾',
  },
  {
    country: 'Maldives',
    code: 'MV',
    value: '+960',
    icon: '🇲🇻',
  },
  {
    country: 'Mali',
    code: 'ML',
    value: '+223',
    icon: '🇲🇱',
  },
  {
    country: 'Malta',
    code: 'MT',
    value: '+356',
    icon: '🇲🇹',
  },
  {
    country: 'Marshall Islands',
    code: 'MH',
    value: '+692',
    icon: '🇲🇭',
  },
  {
    country: 'Mauritania',
    code: 'MR',
    value: '+222',
    icon: '🇲🇷',
  },
  {
    country: 'Mauritius',
    code: 'MU',
    value: '+230',
    icon: '🇲🇺',
  },
  {
    country: 'Mexico',
    code: 'MX',
    value: '+52',
    icon: '🇲🇽',
  },
  {
    country: 'Micronesia',
    code: 'FM',
    value: '+691',
    icon: '🇫🇲',
  },
  {
    country: 'Moldova',
    code: 'MD',
    value: '+373',
    icon: '🇲🇩',
  },
  {
    country: 'Monaco',
    code: 'MC',
    value: '+377',
    icon: '🇲🇨',
  },
  {
    country: 'Mongolia',
    code: 'MN',
    value: '+976',
    icon: '🇲🇳',
  },
  {
    country: 'Montenegro',
    code: 'ME',
    value: '+382',
    icon: '🇲🇪',
  },
  {
    country: 'Morocco',
    code: 'MA',
    value: '+212',
    icon: '🇲🇦',
  },
  {
    country: 'Mozambique',
    code: 'MZ',
    value: '+258',
    icon: '🇲🇿',
  },
  {
    country: 'Myanmar (Burma)',
    code: 'MM',
    value: '+95',
    icon: '🇲🇲',
  },
  {
    country: 'Namibia',
    code: 'NA',
    value: '+264',
    icon: '🇳🇦',
  },
  {
    country: 'Nauru',
    code: 'NR',
    value: '+674',
    icon: '🇳🇷',
  },
  {
    country: 'Nepal',
    code: 'NP',
    value: '+977',
    icon: '🇳🇵',
  },
  {
    country: 'Netherlands',
    code: 'NL',
    value: '+31',
    icon: '🇳🇱',
  },
  {
    country: 'New Zealand',
    code: 'NZ',
    value: '+64',
    icon: '🇳🇿',
  },
  {
    country: 'Nicaragua',
    code: 'NI',
    value: '+505',
    icon: '🇳🇮',
  },
  {
    country: 'Niger',
    code: 'NE',
    value: '+227',
    icon: '🇳🇪',
  },
  {
    country: 'Nigeria',
    code: 'NG',
    value: '+234',
    icon: '🇳🇬',
  },
  {
    country: 'North Korea',
    code: 'KP',
    value: '+850',
    icon: '🇰🇵',
  },
  {
    country: 'North Macedonia',
    code: 'MK',
    value: '+389',
    icon: '🇲🇰',
  },
  {
    country: 'Norway',
    code: 'NO',
    value: '+47',
    icon: '🇳🇴',
  },
  {
    country: 'Oman',
    code: 'OM',
    value: '+968',
    icon: '🇴🇲',
  },
  {
    country: 'Pakistan',
    code: 'PK',
    value: '+92',
    icon: '🇵🇰',
  },
  {
    country: 'Palau',
    code: 'PW',
    value: '+680',
    icon: '🇵🇼',
  },
  {
    country: 'Palestine',
    code: 'PS',
    value: '+970',
    icon: '🇵🇸',
  },
  {
    country: 'Panama',
    code: 'PA',
    value: '+507',
    icon: '🇵🇦',
  },
  {
    country: 'Papua New Guinea',
    code: 'PG',
    value: '+675',
    icon: '🇵🇬',
  },
  {
    country: 'Paraguay',
    code: 'PY',
    value: '+595',
    icon: '🇵🇾',
  },
  {
    country: 'Peru',
    code: 'PE',
    value: '+51',
    icon: '🇵🇪',
  },
  {
    country: 'Philippines',
    code: 'PH',
    value: '+63',
    icon: '🇵🇭',
  },
  {
    country: 'Poland',
    code: 'PL',
    value: '+48',
    icon: '🇵🇱',
  },
  {
    country: 'Portugal',
    code: 'PT',
    value: '+351',
    icon: '🇵🇹',
  },
  {
    country: 'Qatar',
    code: 'QA',
    value: '+974',
    icon: '🇶🇦',
  },
  {
    country: 'Romania',
    code: 'RO',
    value: '+40',
    icon: '🇷🇴',
  },
  {
    country: 'Russia',
    code: 'RU',
    value: '+7',
    icon: '🇷🇺',
  },
  {
    country: 'Rwanda',
    code: 'RW',
    value: '+250',
    icon: '🇷🇼',
  },
  {
    country: 'Saint Kitts and Nevis',
    code: 'KN',
    value: '+1-869',
    icon: '🇰🇳',
  },
  {
    country: 'Saint Lucia',
    code: 'LC',
    value: '+1-758',
    icon: '🇱🇨',
  },
  {
    country: 'Saint Vincent and the Grenadines',
    code: 'VC',
    value: '+1-784',
    icon: '🇻🇨',
  },
  {
    country: 'Samoa',
    code: 'WS',
    value: '+685',
    icon: '🇼🇸',
  },
  {
    country: 'San Marino',
    code: 'SM',
    value: '+378',
    icon: '🇸🇲',
  },
  {
    country: 'Sao Tome and Principe',
    code: 'ST',
    value: '+239',
    icon: '🇸🇹',
  },
  {
    country: 'Saudi Arabia',
    code: 'SA',
    value: '+966',
    icon: '🇸🇦',
  },
  {
    country: 'Senegal',
    code: 'SN',
    value: '+221',
    icon: '🇸🇳',
  },
  {
    country: 'Serbia',
    code: 'RS',
    value: '+381',
    icon: '🇷🇸',
  },
  {
    country: 'Seychelles',
    code: 'SC',
    value: '+248',
    icon: '🇸🇨',
  },
  {
    country: 'Sierra Leone',
    code: 'SL',
    value: '+232',
    icon: '🇸🇱',
  },
  {
    country: 'Singapore',
    code: 'SG',
    value: '+65',
    icon: '🇸🇬',
  },
  {
    country: 'Slovakia',
    code: 'SK',
    value: '+421',
    icon: '🇸🇰',
  },
  {
    country: 'Slovenia',
    code: 'SI',
    value: '+386',
    icon: '🇸🇮',
  },
  {
    country: 'Solomon Islands',
    code: 'SB',
    value: '+677',
    icon: '🇸🇧',
  },
  {
    country: 'Somalia',
    code: 'SO',
    value: '+252',
    icon: '🇸🇴',
  },
  {
    country: 'South Africa',
    code: 'ZA',
    value: '+27',
    icon: '🇿🇦',
  },
  {
    country: 'South Korea',
    code: 'KR',
    value: '+82',
    icon: '🇰🇷',
  },
  {
    country: 'South Sudan',
    code: 'SS',
    value: '+211',
    icon: '🇸🇸',
  },
  {
    country: 'Spain',
    code: 'ES',
    value: '+34',
    icon: '🇪🇸',
  },
  {
    country: 'Sri Lanka',
    code: 'LK',
    value: '+94',
    icon: '🇱🇰',
  },
  {
    country: 'Sudan',
    code: 'SD',
    value: '+249',
    icon: '🇸🇩',
  },
  {
    country: 'Suriname',
    code: 'SR',
    value: '+597',
    icon: '🇸🇷',
  },
  {
    country: 'Sweden',
    code: 'SE',
    value: '+46',
    icon: '🇸🇪',
  },
  {
    country: 'Switzerland',
    code: 'CH',
    value: '+41',
    icon: '🇨🇭',
  },
  {
    country: 'Syria',
    code: 'SY',
    value: '+963',
    icon: '🇸🇾',
  },
  {
    country: 'Taiwan',
    code: 'TW',
    value: '+886',
    icon: '🇹🇼',
  },
  {
    country: 'Tajikistan',
    code: 'TJ',
    value: '+992',
    icon: '🇹🇯',
  },
  {
    country: 'Tanzania',
    code: 'TZ',
    value: '+255',
    icon: '🇹🇿',
  },
  {
    country: 'Thailand',
    code: 'TH',
    value: '+66',
    icon: '🇹🇭',
  },
  {
    country: 'Timor-Leste',
    code: 'TL',
    value: '+670',
    icon: '🇹🇱',
  },
  {
    country: 'Togo',
    code: 'TG',
    value: '+228',
    icon: '🇹🇬',
  },
  {
    country: 'Tonga',
    code: 'TO',
    value: '+676',
    icon: '🇹🇴',
  },
  {
    country: 'Trinidad and Tobago',
    code: 'TT',
    value: '+1-868',
    icon: '🇹🇹',
  },
  {
    country: 'Tunisia',
    code: 'TN',
    value: '+216',
    icon: '🇹🇳',
  },
  {
    country: 'Turkey',
    code: 'TR',
    value: '+90',
    icon: '🇹🇷',
  },
  {
    country: 'Turkmenistan',
    code: 'TM',
    value: '+993',
    icon: '🇹🇲',
  },
  {
    country: 'Tuvalu',
    code: 'TV',
    value: '+688',
    icon: '🇹🇻',
  },
  {
    country: 'Uganda',
    code: 'UG',
    value: '+256',
    icon: '🇺🇬',
  },
  {
    country: 'Ukraine',
    code: 'UA',
    value: '+380',
    icon: '🇺🇦',
  },
  {
    country: 'United Arab Emirates',
    code: 'AE',
    value: '+971',
    icon: '🇦🇪',
  },
  {
    country: 'United Kingdom',
    code: 'GB',
    value: '+44',
    icon: '🇬🇧',
  },
  {
    country: 'United States',
    code: 'US',
    value: '+1',
    icon: '🇺🇸',
  },
  {
    country: 'Uruguay',
    code: 'UY',
    value: '+598',
    icon: '🇺🇾',
  },
  {
    country: 'Uzbekistan',
    code: 'UZ',
    value: '+998',
    icon: '🇺🇿',
  },
  {
    country: 'Vanuatu',
    code: 'VU',
    value: '+678',
    icon: '🇻🇺',
  },
  {
    country: 'Vatican City',
    code: 'VA',
    value: '+379',
    icon: '🇻🇦',
  },
  {
    country: 'Venezuela',
    code: 'VE',
    value: '+58',
    icon: '🇻🇪',
  },
  {
    country: 'Vietnam',
    code: 'VN',
    value: '+84',
    icon: '🇻🇳',
  },
  {
    country: 'Yemen',
    code: 'YE',
    value: '+967',
    icon: '🇾🇪',
  },
  {
    country: 'Zambia',
    code: 'ZM',
    value: '+260',
    icon: '🇿🇲',
  },
  {
    country: 'Zimbabwe',
    code: 'ZW',
    value: '+263',
    icon: '🇿🇼',
  },
];

export const whatsappMessage = '*اهلا بك في اورى*\n\nكيف بمكننا مساعدتك';
export const whatsappPhone =
  process.env.NEXT_PUBLIC_WHATSAPP_PHONE || '249999094668';
